In [ ]:

!pip install tensorflow

In [ ]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.
import tensorflow as tf

scalar = tf.constant(10)
print(scalar.numpy(),scalar.dtype)

10 <dtype: 'int32'>


In [ ]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.
vector = tf.constant([2,4,6,8])
print(vector.shape,vector.numpy())

(4,) [2 4 6 8]


In [ ]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.
matrix = tf.constant([[1, 2] , [3,4]])
print(matrix.shape,matrix.dtype)

(2, 2) <dtype: 'int32'>


In [ ]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.
weight = tf.Variable([5.0], name="weight")
print(weight.numpy())

[5.]


In [ ]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.
weight.assign([10.0])
print(weight.numpy())

[10.]


In [ ]:
# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.
weight = tf.Variable([[1.0, 2.0],[3.0,4.0]], name="weight")

weight.assign_add([[1.0,1.0],[1.0,1.0]])

print(weight)


<tf.Variable 'weight:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>


In [3]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().
import tensorflow as tf

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

matmul = tf.matmul(matrix1, matrix2)
print(matmul.numpy())


[[19 22]
 [43 50]]


In [4]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.
import tensorflow as tf

# Create a random tensor of shape (3, 3)
tensor = tf.random.uniform(shape=(3, 3))

# Print details
print("Shape:", tensor.shape)
print("Dtype:", tensor.dtype)
print("Values:\n", tensor.numpy())


Shape: (3, 3)
Dtype: <dtype: 'float32'>
Values:
 [[0.47711062 0.75144327 0.14049506]
 [0.833768   0.12794232 0.45556295]
 [0.03321648 0.6863458  0.6657462 ]]
