In [3]:
# Q1: Create a DataFrame with the following e-commerce sales data:
# Columns: OrderID, CustomerID, Product, Category, Quantity, Price, OrderDate, Rating, Review
# Create at least 50 sample records with realistic data including dates from 2023-2024
# Display the first 10 and last 5 records using head() and tail()

import pandas as pd

data = [
    [1001, "C001", "Laptop", "Electronics", 1, 75000, "2023-01-15", 5, "Excellent performance"],
    [1002, "C002", "Smartphone", "Electronics", 2, 45000, "2023-01-20", 4, "Good value"],
    [1003, "C003", "Headphones", "Accessories", 1, 2500, "2023-02-05", 4, "Nice sound"],
    [1004, "C004", "Keyboard", "Accessories", 1, 1800, "2023-02-12", 3, "Average quality"],
    [1005, "C005", "Mouse", "Accessories", 2, 900, "2023-02-18", 5, "Very smooth"],
    [1006, "C006", "Monitor", "Electronics", 1, 12000, "2023-03-01", 4, "Clear display"],
    [1007, "C007", "Tablet", "Electronics", 1, 22000, "2023-03-08", 4, "Fast and handy"],
    [1008, "C008", "Printer", "Electronics", 1, 8500, "2023-03-15", 3, "Works fine"],
    [1009, "C009", "Webcam", "Accessories", 1, 3200, "2023-03-22", 4, "Good clarity"],
    [1010, "C010", "Router", "Electronics", 1, 2800, "2023-04-01", 5, "Strong signal"],

    [1011, "C011", "Shoes", "Fashion", 1, 3000, "2023-04-10", 4, "Comfortable"],
    [1012, "C012", "T-shirt", "Fashion", 3, 1500, "2023-04-18", 5, "Great fabric"],
    [1013, "C013", "Jeans", "Fashion", 2, 2400, "2023-05-01", 4, "Perfect fit"],
    [1014, "C014", "Jacket", "Fashion", 1, 4200, "2023-05-10", 5, "Stylish"],
    [1015, "C015", "Watch", "Accessories", 1, 5500, "2023-05-20", 4, "Looks premium"],

    [1016, "C016", "Backpack", "Accessories", 1, 2800, "2023-06-01", 5, "Very durable"],
    [1017, "C017", "Water Bottle", "Home", 2, 800, "2023-06-12", 4, "Good quality"],
    [1018, "C018", "Vacuum Cleaner", "Home", 1, 9500, "2023-06-22", 4, "Strong suction"],
    [1019, "C019", "Mixer Grinder", "Home", 1, 6500, "2023-07-01", 5, "Powerful motor"],
    [1020, "C020", "Air Fryer", "Home", 1, 9000, "2023-07-10", 4, "Healthy cooking"],

    [1021, "C021", "Book", "Education", 2, 1200, "2023-08-01", 5, "Very informative"],
    [1022, "C022", "Notebook", "Education", 5, 500, "2023-08-10", 4, "Good paper"],
    [1023, "C023", "Pen Set", "Education", 3, 300, "2023-08-18", 3, "Average"],
    [1024, "C024", "Desk Lamp", "Home", 1, 1500, "2023-09-01", 4, "Bright light"],
    [1025, "C025", "Office Chair", "Furniture", 1, 12000, "2023-09-10", 5, "Very comfortable"],

    [1026, "C026", "Sofa", "Furniture", 1, 35000, "2023-10-01", 4, "Soft cushions"],
    [1027, "C027", "Dining Table", "Furniture", 1, 28000, "2023-10-12", 5, "Solid build"],
    [1028, "C028", "Bed Lamp", "Home", 2, 2200, "2023-10-20", 4, "Nice design"],
    [1029, "C029", "Curtains", "Home", 3, 1800, "2023-11-01", 4, "Good fabric"],
    [1030, "C030", "Carpet", "Home", 1, 4200, "2023-11-10", 5, "Looks elegant"],

    [1031, "C031", "Gaming Console", "Electronics", 1, 45000, "2023-12-01", 5, "Amazing experience"],
    [1032, "C032", "Game Controller", "Electronics", 2, 5000, "2023-12-10", 4, "Responsive"],
    [1033, "C033", "TV", "Electronics", 1, 65000, "2023-12-20", 5, "Crystal clear"],

    [1034, "C034", "Smartwatch", "Electronics", 1, 12000, "2024-01-05", 4, "Very useful"],
    [1035, "C035", "Bluetooth Speaker", "Electronics", 1, 6500, "2024-01-15", 5, "Great sound"],
    [1036, "C036", "Power Bank", "Accessories", 2, 3000, "2024-01-25", 4, "Fast charging"],
    [1037, "C037", "Fitness Band", "Electronics", 1, 4500, "2024-02-05", 4, "Tracks well"],
    [1038, "C038", "Earbuds", "Accessories", 1, 5500, "2024-02-15", 5, "Excellent bass"],

    [1039, "C039", "Desk Organizer", "Home", 2, 1200, "2024-02-25", 4, "Very handy"],
    [1040, "C040", "Wall Clock", "Home", 1, 1800, "2024-03-05", 3, "Looks fine"],
    [1041, "C041", "Calendar", "Home", 1, 500, "2024-03-12", 4, "Useful"],
    [1042, "C042", "Photo Frame", "Home", 2, 900, "2024-03-18", 5, "Nice finish"],
    [1043, "C043", "Table Fan", "Home", 1, 3500, "2024-03-25", 4, "Cools well"],

    [1044, "C044", "Helmet", "Automotive", 1, 2800, "2024-04-01", 5, "Very safe"],
    [1045, "C045", "Car Vacuum", "Automotive", 1, 4200, "2024-04-10", 4, "Strong suction"],
    [1046, "C046", "Bike Cover", "Automotive", 1, 1500, "2024-04-18", 4, "Good fit"],
    [1047, "C047", "Phone Holder", "Automotive", 2, 800, "2024-05-01", 3, "Average"],
    [1048, "C048", "Dash Camera", "Automotive", 1, 9500, "2024-05-10", 5, "Very clear"],

    [1049, "C049", "Tool Kit", "Hardware", 1, 3500, "2024-05-20", 4, "Useful tools"],
    [1050, "C050", "Drill Machine", "Hardware", 1, 7800, "2024-06-01", 5, "Powerful"]
]

columns = ["OrderID", "CustomerID", "Product", "Category", "Quantity", "Price", "OrderDate", "Rating", "Review"]

df = pd.DataFrame(data, columns=columns)

df["OrderDate"] = pd.to_datetime(df["OrderDate"])

# Display the first 10 and last 5 records using head() and tail()
print(df.head(10))
print(df.tail(5))


   OrderID CustomerID     Product     Category  Quantity  Price  OrderDate  \
0     1001       C001      Laptop  Electronics         1  75000 2023-01-15   
1     1002       C002  Smartphone  Electronics         2  45000 2023-01-20   
2     1003       C003  Headphones  Accessories         1   2500 2023-02-05   
3     1004       C004    Keyboard  Accessories         1   1800 2023-02-12   
4     1005       C005       Mouse  Accessories         2    900 2023-02-18   
5     1006       C006     Monitor  Electronics         1  12000 2023-03-01   
6     1007       C007      Tablet  Electronics         1  22000 2023-03-08   
7     1008       C008     Printer  Electronics         1   8500 2023-03-15   
8     1009       C009      Webcam  Accessories         1   3200 2023-03-22   
9     1010       C010      Router  Electronics         1   2800 2023-04-01   

   Rating                 Review  
0       5  Excellent performance  
1       4             Good value  
2       4             Nice sound  
3

In [4]:
# Q2: Use info() and describe() to get a comprehensive overview of the dataset
# Identify data types, missing values, and statistical summary
# Print the column names using columns attribute and shape of the dataset

# Basic info
print(df.info())

# Summary statistics
print(df.describe())

# Column names
print(df.columns)

# Shape of dataset (rows, columns)
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   OrderID     50 non-null     int64         
 1   CustomerID  50 non-null     object        
 2   Product     50 non-null     object        
 3   Category    50 non-null     object        
 4   Quantity    50 non-null     int64         
 5   Price       50 non-null     int64         
 6   OrderDate   50 non-null     datetime64[ns]
 7   Rating      50 non-null     int64         
 8   Review      50 non-null     object        
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 3.6+ KB
None
          OrderID   Quantity         Price            OrderDate     Rating
count    50.00000  50.000000     50.000000                   50  50.000000
mean   1025.50000   1.420000   9802.000000  2023-09-20 23:31:12   4.280000
min    1001.00000   1.000000    300.000000  2023-01-15 00:00:00   3.000

In [ ]:
# Q3: Introduce 10% missing values randomly in Rating and Review columns
# Detect missing values and display the count of missing values per column
# Fill missing ratings with the median rating and missing reviews with "No review provided"


In [10]:
# Q4: Create a new column 'TotalAmount' by multiplying Quantity and Price
# Add another column 'DiscountedPrice' that applies 10% discount on orders above $100
# Use conditional selection to filter orders where TotalAmount > $150

df["TotalAmount"] = df["Quantity"] * df["Price"]

df["DiscountedPrice"] = df["TotalAmount"].where(
    df["TotalAmount"] <= 8000,
    df["TotalAmount"] * 0.9
)

print(df[df['TotalAmount'] > 12000])




    OrderID CustomerID         Product     Category  Quantity  Price  \
0      1001       C001          Laptop  Electronics         1  75000   
1      1002       C002      Smartphone  Electronics         2  45000   
6      1007       C007          Tablet  Electronics         1  22000   
25     1026       C026            Sofa    Furniture         1  35000   
26     1027       C027    Dining Table    Furniture         1  28000   
30     1031       C031  Gaming Console  Electronics         1  45000   
32     1033       C033              TV  Electronics         1  65000   

    OrderDate  Rating                 Review  TotalAmount  DiscountedPrice  
0  2023-01-15       5  Excellent performance        75000            67500  
1  2023-01-20       4             Good value        90000            81000  
6  2023-03-08       4         Fast and handy        22000            19800  
25 2023-10-01       4          Soft cushions        35000            31500  
26 2023-10-12       5            Solid

In [14]:
# Q5: Select only the columns: Product, Category, TotalAmount, and Rating
# Filter and display all orders from the 'Electronics' category with Rating >= 4

selected_df = df[['Product','Category','TotalAmount','Rating']]

result = selected_df[
    (selected_df['Category'] == 'Electronics') &
    (selected_df['Rating'] >= 4)
]

print(result)

              Product     Category  TotalAmount  Rating
0              Laptop  Electronics        75000       5
1          Smartphone  Electronics        90000       4
5             Monitor  Electronics        12000       4
6              Tablet  Electronics        22000       4
9              Router  Electronics         2800       5
30     Gaming Console  Electronics        45000       5
31    Game Controller  Electronics        10000       4
32                 TV  Electronics        65000       5
33         Smartwatch  Electronics        12000       4
34  Bluetooth Speaker  Electronics         6500       5
36       Fitness Band  Electronics         4500       4


In [15]:
# Q6: Use boolean indexing to find all orders where:
# - Quantity > 2 AND Price < 50 OR Rating == 5
# Display the count of such orders

filtered_orders = df[
    ((df["Quantity"] > 2) & (df["Price"] < 50)) |
    (df["Rating"] == 5)
]

count_orders = filtered_orders.shape[0]
print("Number of matching orders:", count_orders)


Number of matching orders: 19


In [19]:
# Q7: Sort the entire DataFrame by OrderDate (descending) and then by TotalAmount (descending)
# Create a new column 'SalesRank' that ranks products by TotalAmount in descending order

print(df.sort_values(by=['OrderDate', 'TotalAmount'], ascending=[False, False]))

df['SaleRank'] = df['TotalAmount'].rank(ascending=False)
print(df)




    OrderID CustomerID            Product     Category  Quantity  Price  \
49     1050       C050      Drill Machine     Hardware         1   7800   
48     1049       C049           Tool Kit     Hardware         1   3500   
47     1048       C048        Dash Camera   Automotive         1   9500   
46     1047       C047       Phone Holder   Automotive         2    800   
45     1046       C046         Bike Cover   Automotive         1   1500   
44     1045       C045         Car Vacuum   Automotive         1   4200   
43     1044       C044             Helmet   Automotive         1   2800   
42     1043       C043          Table Fan         Home         1   3500   
41     1042       C042        Photo Frame         Home         2    900   
40     1041       C041           Calendar         Home         1    500   
39     1040       C040         Wall Clock         Home         1   1800   
38     1039       C039     Desk Organizer         Home         2   1200   
37     1038       C038   

In [18]:
# Q8: Find the top 5 best-selling products based on total quantity sold
# Display the product name and total quantity in descending order

product_sales = df.groupby("Product")["Quantity"].sum()

product_sales_sorted = product_sales.sort_values(ascending=False)

top_5_products = product_sales_sorted.head(5)

print(top_5_products)

Product
Notebook           5
Curtains           3
Pen Set            3
T-shirt            3
Game Controller    2
Name: Quantity, dtype: int64


In [20]:
# Q9: Group the data by 'Category' and calculate:
# - Total sales (sum of TotalAmount)
# - Average rating
# - Number of orders
# Display the results sorted by total sales

category_summary = df.groupby("Category").agg(
    TotalSales=("TotalAmount", "sum"),
    AverageRating=("Rating", "mean"),
    NumberOfOrders=("OrderID", "count")
)

category_summary_sorted = category_summary.sort_values(
    by="TotalSales",
    ascending=False
)

print(category_summary_sorted)



             TotalSales  AverageRating  NumberOfOrders
Category                                              
Electronics      353300       4.333333              12
Furniture         75000       4.666667               3
Home              52100       4.153846              13
Accessories       29100       4.250000               8
Automotive        19600       4.200000               5
Fashion           16500       4.500000               4
Hardware          11300       4.500000               2
Education          5800       4.000000               3


In [22]:
# Q10: Create a pivot table showing average Price for each Category and Rating combination
# Use groupby with multiple columns (Category, Product) and aggregate multiple functions

pivot_avg_price = pd.pivot_table(
    df,
    values="Price",
    index="Category",
    columns="Rating",
    aggfunc="mean"
)

print(pivot_avg_price)

category_product_summary = df.groupby(
    ["Category", "Product"]
).agg(
    TotalQuantity=("Quantity", "sum"),
    TotalSales=("TotalAmount", "sum"),
    AveragePrice=("Price", "mean"),
    AverageRating=("Rating", "mean")
)

print(category_product_summary)



Rating            3             4             5
Category                                       
Accessories  1800.0   3550.000000   3066.666667
Automotive    800.0   2850.000000   6150.000000
Education     300.0    500.000000   1200.000000
Electronics  8500.0  16750.000000  38860.000000
Fashion         NaN   2700.000000   2850.000000
Furniture       NaN  35000.000000  20000.000000
Hardware        NaN   3500.000000   7800.000000
Home         1800.0   3333.333333   3866.666667
                               TotalQuantity  TotalSales  AveragePrice  \
Category    Product                                                      
Accessories Backpack                       1        2800        2800.0   
            Earbuds                        1        5500        5500.0   
            Headphones                     1        2500        2500.0   
            Keyboard                       1        1800        1800.0   
            Mouse                          2        1800         900.0   
  

In [25]:
# Q11: Convert the Quantity and Price columns to NumPy arrays
# Create a 2D array combining these two columns
# Display array properties: shape, dtype, ndim, size
import numpy as np

# Convert Quantity and Price columns to NumPy arrays
quantity_array = np.array(df['Quantity'])
price_array = np.array(df['Price'])

# Create a 2D NumPy array combining both columns
combined_array = np.column_stack((quantity_array, price_array))

# Display array properties
print("Array:")
print(combined_array)

print("\nShape:", combined_array.shape)
print("Data type:", combined_array.dtype)
print("Number of dimensions:", combined_array.ndim)
print("Total elements:", combined_array.size)


Array:
[[    1 75000]
 [    2 45000]
 [    1  2500]
 [    1  1800]
 [    2   900]
 [    1 12000]
 [    1 22000]
 [    1  8500]
 [    1  3200]
 [    1  2800]
 [    1  3000]
 [    3  1500]
 [    2  2400]
 [    1  4200]
 [    1  5500]
 [    1  2800]
 [    2   800]
 [    1  9500]
 [    1  6500]
 [    1  9000]
 [    2  1200]
 [    5   500]
 [    3   300]
 [    1  1500]
 [    1 12000]
 [    1 35000]
 [    1 28000]
 [    2  2200]
 [    3  1800]
 [    1  4200]
 [    1 45000]
 [    2  5000]
 [    1 65000]
 [    1 12000]
 [    1  6500]
 [    2  3000]
 [    1  4500]
 [    1  5500]
 [    2  1200]
 [    1  1800]
 [    1   500]
 [    2   900]
 [    1  3500]
 [    1  2800]
 [    1  4200]
 [    1  1500]
 [    2   800]
 [    1  9500]
 [    1  3500]
 [    1  7800]]

Shape: (50, 2)
Data type: int64
Number of dimensions: 2
Total elements: 100


In [27]:
# Q12: Create a 1D NumPy array of 100 random prices between 10 and 500
# Calculate mean, median, standard deviation, min, and max using NumPy functions
# Reshape this array into a 10x10 matrix

import numpy as np

# Create a 1D NumPy array of 100 random prices between 10 and 500
prices = np.random.uniform(10, 500, 100)

# Calculate statistics
mean_price = np.mean(prices)
median_price = np.median(prices)
std_price = np.std(prices)
min_price = np.min(prices)
max_price = np.max(prices)

# Display statistics
print("Mean:", mean_price)
print("Median:", median_price)
print("Standard Deviation:", std_price)
print("Minimum:", min_price)
print("Maximum:", max_price)

# Reshape into a 10x10 matrix
price_matrix = prices.reshape(10, 10)

print("\n10x10 Price Matrix:")
print(price_matrix)



Mean: 269.636903340819
Median: 277.5756865176637
Standard Deviation: 143.29115604705717
Minimum: 10.828619039257582
Maximum: 489.87130637468033

10x10 Price Matrix:
[[114.26473705  18.36288727 486.74251706 327.2559179  115.116737
  484.49268147 269.1452219  454.35750846 104.19208767 282.95353072]
 [ 39.56910685 127.8367321  115.95814678 471.84100096 454.65384718
  242.53485659 103.08016735 458.13491333 331.87751638 117.87745668]
 [ 31.35005881 122.78583889 276.5720569  464.52530498 389.58981095
  226.83417105 404.06058643 444.2193866  234.87915439 257.83639714]
 [310.41430874  32.97690541  81.50445539 233.54674675 118.38653907
  443.02552726 287.66380466  98.06792118 461.92376149 100.9485129 ]
 [ 10.82861904 259.18639545 344.05696477  81.85709955  71.72073278
  443.91221107  84.56547019 209.4096157   75.00446717 390.24688764]
 [468.13883243 455.77318744 451.29578164 437.71355725 401.43254721
  177.10321994 393.56594953 245.28263979 260.79139939 381.21216172]
 [307.51497621 430.50823082

In [29]:
# Q13: Create two 3D NumPy arrays (3x3x3) with random integers
# Perform element-wise addition, multiplication, and matrix multiplication
# Use boolean indexing to filter values greater than 50 of Matrix 1:", np.linalg.det(mat1))
import numpy as np

array1 = np.random.randint(1, 101, size=(3, 3, 3))
array2 = np.random.randint(1, 101, size=(3, 3, 3))

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)

add_result = array1 + array2
print("\nElement-wise Addition:\n", add_result)

mul_result = array1 * array2
print("\nElement-wise Multiplication:\n", mul_result)

matmul_result = np.matmul(array1, array2)
print("\nMatrix Multiplication:\n", matmul_result)

filtered_values = array1[array1 > 50]
print("\nValues greater than 50 in Array 1:\n", filtered_values)


Array 1:
 [[[61 66 43]
  [82 73 40]
  [89  8 59]]

 [[ 8 97 47]
  [57 63 85]
  [41  6 63]]

 [[72 53 77]
  [83 20 76]
  [51 49 52]]]

Array 2:
 [[[66 25 46]
  [75 77 14]
  [80 17 79]]

 [[34 93 27]
  [48 92 92]
  [15 62 18]]

 [[30 52 36]
  [86 64 39]
  [84 27 58]]]

Element-wise Addition:
 [[[127  91  89]
  [157 150  54]
  [169  25 138]]

 [[ 42 190  74]
  [105 155 177]
  [ 56  68  81]]

 [[102 105 113]
  [169  84 115]
  [135  76 110]]]

Element-wise Multiplication:
 [[[4026 1650 1978]
  [6150 5621  560]
  [7120  136 4661]]

 [[ 272 9021 1269]
  [2736 5796 7820]
  [ 615  372 1134]]

 [[2160 2756 2772]
  [7138 1280 2964]
  [4284 1323 3016]]]

Matrix Multiplication:
 [[[12416  7338  7127]
  [14087  8351  7954]
  [11194  3844  8867]]

 [[ 5633 12582  9986]
  [ 6237 16367  8865]
  [ 2627  8271  2793]]

 [[13186  9215  9125]
  [10594  7648  8176]
  [10112  7192  6763]]]

Values greater than 50 in Array 1:
 [61 66 82 73 89 59 97 57 63 85 63 72 53 77 83 76 51 52]


In [31]:
# Q14: Create NumPy arrays using special values:
# - Array of zeros (5x5)
# - Array of ones (3x4)
# - Identity matrix (4x4)
# - Array with values from 0 to 50 with step of 5 using arange
# Concatenate and stack these arrays
zeros_array = np.zeros((5, 5))
ones_array = np.ones((3, 4))
identity_array = np.eye(4)
range_array = np.arange(0, 51, 5)

print("Zeros Array:\n", zeros_array)
print("\nOnes Array:\n", ones_array)
print("\nIdentity Matrix:\n", identity_array)
print("\nRange Array:\n", range_array)

concat_array = np.concatenate((identity_array, identity_array), axis=0)
print("\nConcatenated Identity Matrices:\n", concat_array)

vstack_array = np.vstack((identity_array, identity_array))
hstack_array = np.hstack((identity_array, identity_array))

print("\nVertical Stack:\n", vstack_array)
print("\nHorizontal Stack:\n", hstack_array)



Zeros Array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Range Array:
 [ 0  5 10 15 20 25 30 35 40 45 50]

Concatenated Identity Matrices:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Vertical Stack:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Horizontal Stack:
 [[1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1.]]


In [32]:
# Q15: Use array slicing to extract:
# - First 3 rows from the Quantity-Price 2D array
# - Every alternate element from the Price array
# - Diagonal elements from a 5x5 matrix of TotalAmount value
qp_array = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400],
    [50, 500]
])

price_array = np.array([100, 200, 300, 400, 500])

total_amount = np.array([
    [10, 20, 30, 40, 50],
    [60, 70, 80, 90, 100],
    [110, 120, 130, 140, 150],
    [160, 170, 180, 190, 200],
    [210, 220, 230, 240, 250]
])

first_three_rows = qp_array[:3, :]
print("First 3 rows:\n", first_three_rows)

alternate_prices = price_array[::2]
print("\nAlternate Price elements:\n", alternate_prices)

diagonal_elements = np.diag(total_amount)
print("\nDiagonal elements:\n", diagonal_elements)


First 3 rows:
 [[ 10 100]
 [ 20 200]
 [ 30 300]]

Alternate Price elements:
 [100 300 500]

Diagonal elements:
 [ 10  70 130 190 250]


In [ ]:
# Q16: Create a correlation matrix between Quantity, Price, Rating, and TotalAmount using NumPy
# Calculate the covariance matrix
# Perform linear algebra operations: determinant and inverse of correlation matrix
